Private ["_m","_side","_u"];

_side = _this;

//--- Loadout - Magazines.
_m = ['aaw_f88_mag'];
_m = _m + ['30Rnd_9x19_MP5'];
_m = _m + ['3aaw_f89_mag'];
_m = _m + ['aaw_mag58_mag'];
_m = _m + ['aaw_HEAT_RAP'];
_m = _m + ['aaw_HEAT_FFV'];
_m = _m + ['30Rnd_556x45_Stanag'];
_m = _m + ['30Rnd_556x45_StanagSD'];
_m = _m + ['30Rnd_9x19_MP5SD'];
_m = _m + ['8Rnd_B_Beneli_74Slug'];
_m = _m + ['5Rnd_762x51_M24'];
_m = _m + ['Laserbatteries'];
_m = _m + ['20Rnd_762x51_DMR'];
_m = _m + ['15Rnd_9x19_M9'];
_m = _m + ['15Rnd_9x19_M9SD'];
_m = _m + ['7Rnd_45ACP_1911'];
_m = _m + ['17Rnd_9x19_glock17'];
_m = _m + ['HandGrenade_West'];
_m = _m + ['10Rnd_127x99_m107'];
_m = _m + ['IR_Strobe_Target'];
_m = _m + ['IR_Strobe_Marker'];
_m = _m + ['SmokeShell'];
_m = _m + ['SmokeShellRed'];
_m = _m + ['SmokeShellGreen'];
_m = _m + ['SmokeShellBlue'];
_m = _m + ['SmokeShellYellow'];
_m = _m + ['SmokeShellOrange'];
_m = _m + ['SmokeShellPurple'];
_m = _m + ['FlareWhite_M203'];
_m = _m + ['FlareYellow_M203'];
_m = _m + ['FlareGreen_M203'];
_m = _m + ['FlareRed_M203'];
_m = _m + ['1Rnd_HE_M203'];
_m = _m + ['1Rnd_Smoke_M203'];
_m = _m + ['1Rnd_SmokeRed_M203'];
_m = _m + ['1Rnd_SmokeGreen_M203'];
_m = _m + ['1Rnd_SmokeYellow_M203'];
_m = _m + ['Mine'];
_m = _m + ['PipeBomb'];
_m = _m + ['Javelin'];

_m = [_m, _side] Call Compile preprocessFile "Common\Config\Config_SortMagazines.sqf";

//--- Loadout - Weapons.
_u = ['M16A2'];
_u = _u + ['AAW_NZDFIW_a1'];
_u = _u + ['AAW_NZDFIW_a1_gla'];
_u = _u + ['AAW_NZDFIW_ACOG'];
_u = _u + ['AAW_NZDFIW_acog_gla'];
_u = _u + ['AAW_f88_AIM'];
_u = _u + ['AAW_f88_AIM_gla'];
_u = _u + ['M4A1_Aim'];
_u = _u + ['M4A1_RCO_GL'];
_u = _u + ['M4A1_HWS_GL_camo'];
_u = _u + ['M4A1_AIM_SD_camo'];
_u = _u + ['MP5A5'];
_u = _u + ['MP5SD'];
_u = _u + ['M1014'];
_u = _u + ['M4SPR'];
_u = _u + ['M24'];
_u = _u + ['M40A3'];
_u = _u + ['DMR'];
_u = _u + ['m107'];
_u = _u + ['AAW_f89_ELCAN'];
_u = _u + ['AAW_f89_ACOG'];
_u = _u + ['AAW_f89_15'];
_u = _u + ['AAW_mag58'];
_u = _u + ['AAW_mag58_ACOG'];
_u = _u + ['AAW_M72a6'];
_u = _u + ['AAW_M2_carlG'];
_u = _u + ['AAW_M2_carlG_optic'];
_u = _u + ['Javelin'];
_u = _u + ['Stinger'];
_u = _u + ['Laserdesignator'];
_u = _u + ['Binocular'];
_u = _u + ['NVGoggles'];
_u = _u + ['Binocular_Vector'];
_u = _u + ['Colt1911'];
_u = _u + ['M9'];
_u = _u + ['M9SD'];
_u = _u + ['glock17_EP1'];
_u = _u + ['ItemCompass'];
_u = _u + ['ItemGPS'];
_u = _u + ['ItemMap'];
_u = _u + ['ItemRadio'];
_u = _u + ['ItemWatch'];
_u = _u + ['MAV_RAVEN_BACKPACK'];
_u = _u + ['US_Assault_Pack_EP1'];
_u = _u + ['US_Assault_Pack_Ammo_EP1'];
_u = _u + ['US_Assault_Pack_AmmoSAW_EP1'];
_u = _u + ['US_Assault_Pack_AT_EP1'];
_u = _u + ['US_Assault_Pack_Explosives_EP1'];
_u = _u + ['US_Patrol_Pack_EP1'];
_u = _u + ['US_Patrol_Pack_Ammo_EP1'];
_u = _u + ['US_Patrol_Pack_Specops_EP1'];
_u = _u + ['US_Backpack_EP1'];
_u = _u + ['US_Backpack_AmmoMG_EP1'];
_u = _u + ['US_Backpack_AT_EP1'];
_u = _u + ['US_Backpack_Specops_EP1'];
_u = _u + ['Tripod_Bag'];
_u = _u + ['M2HD_mini_TriPod_US_Bag_EP1'];
_u = _u + ['M2StaticMG_US_Bag_EP1'];
_u = _u + ['MK19_TriPod_US_Bag_EP1'];
_u = _u + ['TOW_TriPod_US_Bag_EP1'];
_u = _u + ['M252_US_Bag_EP1'];

[_u, _m, _side] Call Compile preprocessFile "Common\Config\Config_SortWeapons.sqf";

//--- Loadout - Templates (note that backpacks content require the weapons to be first), use -1 to use the default BP content.
_u 		= [[['SCAR_L_CQC','Colt1911','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['30Rnd_556x45_Stanag','HandGrenade_West','SmokeShellBlue','7Rnd_45ACP_1911'],[8,2,2,8]]]];
_u = _u + [[['M16A2GL','US_Assault_Pack_Ammo_EP1','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['30Rnd_556x45_Stanag','HandGrenade_West','1Rnd_HE_M203'],[10,2,8]],-1]];
_u = _u + [[['SCAR_L_CQC_Holo','M136','NVGoggles','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['30Rnd_556x45_Stanag','M136'],[6,1]]]];
_u = _u + [[['SCAR_H_CQC_CCO','MAAWS','NVGoggles','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['20rnd_762x51_B_SCAR','MAAWS_HEAT'],[6,2]]]];
_u = _u + [[['M4A3_CCO_EP1','Javelin','NVGoggles','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['30Rnd_556x45_Stanag','Javelin'],[6,1]]]];
_u = _u + [[['SCAR_L_STD_Mk4CQT','Stinger','NVGoggles','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['30Rnd_556x45_Stanag','Stinger'],[6,1]]]];
_u = _u + [[['SCAR_L_CQC','M9','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['30Rnd_556x45_Stanag','Mine','15Rnd_9x19_M9'],[6,3,8]]]];
_u = _u + [[['SCAR_H_CQC_CCO_SD','M9SD','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['20Rnd_762x51_SB_SCAR','PipeBomb','15Rnd_9x19_M9SD'],[6,3,8]]]];
_u = _u + [[['m240_scoped_EP1','Colt1911','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['100Rnd_762x51_M240','SmokeShellBlue','7Rnd_45ACP_1911'],[5,2,8]]]];
_u = _u + [[['M249_m145_EP1','Colt1911','NVGoggles','Binocular','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['200Rnd_556x45_M249','SmokeShellBlue','7Rnd_45ACP_1911'],[5,2,8]]]];
_u = _u + [[['M14_EP1','M9SD','NVGoggles','Binocular_Vector','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['20Rnd_762x51_DMR','HandGrenade_West','15Rnd_9x19_M9SD'],[10,2,8]]]];
_u = _u + [[['M110_TWS_EP1','M9SD','NVGoggles','Binocular_Vector','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['20Rnd_762x51_B_SCAR','HandGrenade_West','15Rnd_9x19_M9SD'],[10,2,8]]]];
_u = _u + [[['m107','M9SD','NVGoggles','Binocular_Vector','ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'],[['10Rnd_127x99_m107','HandGrenade_West','15Rnd_9x19_M9SD'],[10,2,8]]]];

[_u, _side] Call Compile preprocessFile "Common\Config\Config_SetTemplates.sqf";